Develop
ValeriyaKot/learning_app pull request #1
Opened 2021-04-06 10:48 UTC by ValeriyaKot

2021-04-06 13:06 UTC, slava-pasedko requested changes

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/users/serializers.py
> +class EmptySerializer(serializers.Serializer):
What is that

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/users/serializers.py
> +        fields = ('id', 'username', 'email', 'first_name', 'last_name', 'is_active', 'is_staff', 'auth_token', 'profile')
Split the line so it won't be so long

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/users/serializers.py
> +        profile_data = validated_data.pop('profile')
How does a password look in the admin if we open a freshly created user?

I don't see that you're actually hashing the password, f.e.:

```
from django.contrib.auth.hashers import make_password

validated_data['password'] = make_password(validated_data.get('password'))
```

Or is it being hashed somewhere else?

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/models.py
> +    students = models.ManyToManyField(Profile, related_name='students_of_course')
related name "course_students" would be better

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/models.py
> +    answer = models.TextField()
We'd need to determine somehow that the one of the answers is a right answer, don't we?

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/models.py
> +    question = models.ForeignKey(Question, on_delete=models.DO_NOTHING)
Why do we have DO_NOTHING here? Why do we need an answer for a question that's been deleted?

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/models.py
> +    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
Same thing with DO_NOTHING. 

If we're going to add an ability of deleting profile, question or answer we would do it using some bool field like "deleted" but won't delete from database

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/permissions.py
> +        profile = Profile.objects.get(user=request.user)
What if get method doesn't find a profile? The DoesNotExist exception will occur. We'd need to handle that

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/serializers.py
> +    # def update(self, instance, validated_data):
delete comments from PR

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/views.py
> +
pep8; install flake8 and check the repo before pushing & commiting using it

2021-04-06 13:06 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/views.py
> +        teacher = Profile.objects.get(user=request.user)
rename variable to user since at this exact line we don't know whether it student or a teacher yet

2021-04-08 09:54 UTC, slava-pasedko requested changes

2021-04-08 09:54 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/permissions.py
> +            raise ValueError('Profile does not exist')
Why raise ValueError? It's a permission file, where we should return a boolean value which would indicate if request is processed further. 

For example, if request method in SAFE_METHODS, we return True in order to allow performing this request.

If we have a profile, we should check if profile role is teacher. 

But anyway, we have to return True or False, so we can write this like:
`profile = Profile.objects.get(user=request.user)
            return profile.role == 'teacher'`

This way, if user is not a teacher, method will return False and will prevent such requests from users with a role that differ from "teacher".

If case where we don't have a profile, we don't really know what type of user this is. It means that we should prevent such request.

2021-04-08 10:40 UTC, ValeriyaKot commented on pitch-app/pitch/apps/courses/permissions.py
> +            raise ValueError('Profile does not exist')
так а где должен в итоге находиться проверка на учителя в safe_methods?

2021-04-08 13:49 UTC, ValeriyaKot commented
I added has permission, and permissions by actions in CourseDetailView

2021-04-08 14:04 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/urls.py
> +router.register('pitch/edit_courses', views.CourseEditView, basename='edit_courses')
It would be better if course and other model views had only one url per view, f.e.

pitch/courses ---> GET (list), POST (create)
pitch/courses/<:pk>  --- GET (retrieve), PUT & PATCH (update, partial_update), DELETE (destroy)

2021-04-14 11:31 UTC, slava-pasedko commented on pitch-app/pitch/apps/courses/views.py
> +        return Response('Course can add only teacher', status=status.HTTP_400_BAD_REQUEST)
What response would I get if I sent non-valid data? F.e. serializer_is_valid() returns False.

I still get a 400 Bad Request error which is good, but there's a message that says "Course can add only teacher".

Maybe I am a teacher, maybe not, but the cause of 400 error was bad data rather than profile role

2021-04-26 11:34 UTC, merged